---
development:
  cloud_name: imagenesrails
  api_key: '752961562894886'
  api_secret: Ik6IZ4v3mHx3hfXdOWr28EgOXX0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: imagenesrails
  api_key: '752961562894886'
  api_secret: Ik6IZ4v3mHx3hfXdOWr28EgOXX0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: imagenesrails
  api_key: '752961562894886'
  api_secret: Ik6IZ4v3mHx3hfXdOWr28EgOXX0
  enhance_image_tag: true
  static_image_support: false
